name: Tests

on:
  push:
    branches:
      - main
      - dev/**
    paths:
      - "**/workflows/tests.yml"
      - "**/demo/**"
      - "**/include/**"
      - "**/src/**"
      - "**/tests/**"
      - "**/CMakeLists.txt"
      - "!**/*.md"
      - "!**/*.txt"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release

jobs:
  tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Test
        run: ctest --test-dir build --build-config ${{ env.BUILD_TYPE }} --output-on-failure
